app = "midwaycc-preview"
kill_signal = "SIGINT"
kill_timeout = 10
processes = []

[env]
  NODE_ENV = "development"
  NODE_OPTIONS = "--max-old-space-size=1024"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"

  [services.script_checks]
    command       = "/app/scripts/preview-heartbeat.sh"
    grace_period  = "2m"
    interval      = "30s"
    restart_limit = 10
    timeout       = "30s"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
