app = "midwaycc-preview"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  NODE_ENV = "development"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"

  [services.script_checks]
    command       = "scripts/preview-heartbeat.sh"
    grace_period  = "30s"
    interval      = "10s"
    restart_limit = 6
    timeout       = "10s"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
