backend:
  name: git-gateway
  branch: master

site_url: https://midwaycc.netlify.com
media_folder: static/img
public_folder: /img

collections:
  - name: "nav-items"
    label: "Navigation"
    folder: 'cms/nav'
    format: 'yaml'
    create: false
    delete: false
    widget: "list"
    identifier_field: 'text'
    fields:
      - { label: 'Title', name: 'title', widget: 'hidden', default: 'Main Navigation' }
      - label: 'Navigation Items'
        label_singular: 'Navigation'
        name: 'navigation'
        widget: 'list'
        types:
          - label: 'Plain link'
            name: 'link-item'
            widget: 'object'
            fields:
              - { label: Text, name: text, widget: string }
              - { label: Link, name: link, widget: string }
          - label: 'Menu with sub-items'
            name: 'menu-item'
            widget: 'object'
            fields:
              - { label: Text, name: text, widget: string }
              - label: "Items"
                name: 'items'
                widget: 'list'
                fields: 
                  - { label: Text, name: text, widget: string }
                  - { label: Link, name: link, widget: string }
